exports("GetFaction", getFaction)
exports("getFaction", getFaction)
exports("GetJob2", getFaction)
exports("getJob2", getFaction)
exports("SetFaction", setFaction)
exports("setFaction", setFaction)
exports("SetJob2", setFaction)
exports("setJob2", setFaction)
